FORMAT: 1A
HOST: https://systemgenerowaniakartczasupracy.apiblueprint.org/

# System generowania kart czasu pracy

Opis aplikacji

` `

**Allowed HTTPs requests:**

`PUT`

`POST`

`GET`

`DELETE`

` `

**Description of usual server responses:**

`100` Continue

`200` OK

`201` Created

`204` No Content

`400` Bad Request

`403` Forbidden

`404` Not Found

`405` Method Not Allowed

`500` Internal Server Error

`502` Bad Gateway

`503` Service Unavailable

` `

## Employees Data [/employees]

### List All Employees [GET]
+ Request (application/json)
    + Headers
            
            Authentication: Token
        
+ Response 200 (application/json)
    
    + Body
    
            {    
                [
                    {
                        "Message": "List of all employees: ",
                        "employees": 
                        [
                            {
                                "EmployeeID": 10010422,
                                "Login": "jankow4822",
                                "Department": "DepA",
                                "ManagerID": 101,
                                "PositionID": 53
                            
                            }, {
                                "choice": "Python",
                                "votes": 1024
                            }, {
                                "choice": "Objective-C",
                                "votes": 512
                            }, 
                        ]
                    }
                ]
            }
            
+ Response 400 (application/json)

    + Body
    
            {
                "Massage": "Bad Request"
            }
      
            
### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }