FORMAT: 1A
HOST: https://systemgenerowaniakartczasupracy.apiblueprint.org/

# WeWork

It is an API of *WeWork* - System of generating employee's clockcards

# Group Log-in-out

## Log-in [/login/{?log,pass}]

### Login [POST]
+ Parameters
    
    + log: user1 (string) - User's login to System
    + pass: pass1 (string) - User's password to System
    
+ Response 200 (application/json)

        {
            "Token": 1234567890,
            "AccountType": "Employee"
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }
        
+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
        
## Log-out [/logout]

### Logout [DELETE]
+ Response 200 (application/json)

        {
            "Message": "Logout: Done"
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

# Group User API

## User [/users/{?Login,Password,FirstName,LastName,AccountType,Email,AccountNo}]

+ Parameters

    + Login (string) - User's login
    + Password (int) - User's password
    + FirstName (string) - User's first name
    + LastName (string) - User's last name
    + AccountType (enum) - User's type of account
    + Email (string) - User's e-mail address
    + AccountNo (string) - User's login

### Add New User [POST]
+ Request

        {
            "Login": "jankow4822",
            "Password": 4932
            "FirstName": "Jan",
            "LastName": "Kowalski",
            "AccountType": "Employee",
            "E-mail": "jankowalski@gmail.com",
            "AccountNo": "PL11240000000000009999117429"
        }
        
+ Response 201 (application/json)

        {
            "ID": 1,
            "Login": "jankow4822",
            "Password": 4932
            "FirstName": "Jan",
            "LastName": "Kowalski",
            "AccountType": "Employee",
            "E-mail": "jankowalski@gmail.com",
            "AccountNo": "PL11240000000000009999117429"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }
        
+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
        
### Edit User [PUT]
+ Request

        {
            "Login": "jankow4822",
            "Password": 4932
            "FirstName": "Janusz",
            "LastName": "Kowalski",
            "AccountType": "Employee",
            "E-mail": "januszkowalski@gmail.com",
            "AccountNo": "PL11240000000000009999117429"
        }
        
+ Response 200 (application/json)

        {
            "ID": 1,
            "Login": "jankow4822",
            "Password": 4932
            "FirstName": "Janusz",
            "LastName": "Kowalski",
            "AccountType": "Employee",
            "E-mail": "januszkowalski@gmail.com",
            "AccountNo": "PL11240000000000009999117429"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }
        
+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
        
### Delete User [DELETE]
+ Request

        {
           "ID": 1
        }
        
+ Response 200 (application/json)

        {
            "Login": "jankow4822",
            "Password": 4932
            "FirstName": "Janusz",
            "LastName": "Kowalski",
            "AccountType": "Employee",
            "E-mail": "januszkowalski@gmail.com",
            "AccountNo": "PL11240000000000009999117429"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }
        
+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### List All Users [GET]
+ Response 200 (application/json)

        {
            "ID": 1,
            "Login": "jankow4822",
            "Password": 4932
            "FirstName": "Jan",
            "LastName": "Kowalski",
            "AccountType": "Employee",
            "E-mail": "jankowalski@gmail.com",
            "AccountNo": "PL11240000000000009999117429"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
        

# Group Employee API

## Employee [/employee/{?EmployeeID,Login,Department,ManagerID,PositionID}]

+ Parameters

    + EmployeeID (int) - Employee's ID
    + Login (string) - Employee's login
    + Department (string) - Employee's department
    + ManagerID (int) - Employee's manager's ID
    + PositionID (int) - Employee's position's ID

### Add New Employee [POST]
+ Request

        {
            "Login": "jankow4822",
            "Department": "DepA",
            "ManagerID": 101,
            "PositionID": 53
        }
        
+ Response 201 (application/json)

        {
            "EmployeeID": 10010422,
            "Login": "jankow4822",
            "Department": "DepA",
            "ManagerID": 101,
            "PositionID": 53
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }
        
+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
        
### Edit Employee [PUT]
+ Request

        {
            "EmployeeID": 10010422,
            "Login": "jankow4822",
            "Department": "DepA",
            "ManagerID": 101,
            "PositionID": 53
        }
        
+ Response 200 (application/json)

        {
            "EmployeeID": 10010422,  
            "EmployeeID": 10010422,
            "Login": "jankow4822",
            "Department": "DepA",
            "ManagerID": 101,
            "PositionID": 53
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### Delete Employee [DELETE]
+ Request

        {
            "EmployeeID": 10010422
        }
        
+ Response 200 (application/json)

        {
            "Login": "jankow4822",
            "Department": "DepA",
            "ManagerID": 101,
            "PositionID": 53
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### List All Employees [GET]
+ Response 200 (application/json)

    + Body

            {    
                [
                    {
                        "Message": "List of all employees: ",
                        "employees": 
                        [
                            {
                                "EmployeeID": 10010422,
                                "Login": "jankow4822",
                                "Department": "DepA",
                                "ManagerID": 101,
                                "PositionID": 53
                            }, {
                                "EmployeeID": 10010432,
                                "Login": "jankow4822",
                                "Department": "DepA",
                                "ManagerID": 101,
                                "PositionID": 53
                            }, {
                                "EmployeeID": 10010420,
                                "Login": "jankow4822",
                                "Department": "DepA",
                                "ManagerID": 101,
                                "PositionID": 53
                            }, 
                        ]
                    }
                ]
            }
            
+ Response 400 ((application/json)

        {
            "Message": "Bad Request"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

## Employee - me at day [/employee/meatday]

### Read Employee at day [GET]
+ Request
    
        {
            "day": 25,
            "month": 4,
            "year": 2022
        }

+ Response 200 (application/json)

    + Body

            {   
                "Message" : "Arrives and departures at day"
                "registers" :
                [
                    {
                        "EmployeeID": 10010422,
                        "TimeIn": 0801,
                        "TimeOut": 0912
                    }, {
                        "EmployeeID": 10010422,
                        "TimeIn": 1000,
                        "TimeOut": 1400
                    }, {
                        "EmployeeID": 10010422,
                        "TimeIn": 1430,
                        "TimeOut": 1600
                    }, 
                ]
            }
            
+ Response 400 ((application/json)

        {
            "Message": "Bad Request"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

# Group Manager API

## Manager [/managers/{?ManagerID,Login}]

+ Parameters

    + ManagerID (int) - Manager's ID
    + Login (string) - Manager's login

### Add New Manager [POST]
+ Request

        {
            "Login": "man01"
        }
        
+ Response 201 (application/json)

        {
            "ManagerID": 1,
            "Login": "man01"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### Delete Manager [DELETE]
+ Request

        {
            "ManagerID": 1
        }
        
+ Response 200 (application/json)

        {
            "Meesage": "Delete: Done."
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

# Group Position API

## Position [/positions/{?PositionID,PositionName,Salary}]

+ Parameters

    + PositionID (int) - Position's ID
    + PositionName (string) - Position name's
    + Salary (int) - Salary assigned to position

### List All Positions [GET]
+ Response 200 (application/json)

        {
        
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
        

# Group Gate API

## Gate [/gates/{?GateID,Login}]

+ Parameters

    + GateID (int) - Gate's ID
    + Login (string) - User's login


# Group Register API

## Register [/registers/{?RegisterID,EmployeeID,GateID,DateIn,TimeIn,DateOut,TimeOut}]

+ Parameters

    + RegisterID (int) - Register's ID
    + EmployeeID (int) - Employee's ID
    + GateID (int) - Gate's ID
    + DateIn (date) - Start date of work
    + TimeIn (time) - Start time of work
    + DateOut (date) - End date of work
    + TimeOut (time) - End time of work

### Add New Register [POST]
+ Request

        {
            "GateID": 1,
            "DateIn": "2023-01-01",
            "HourIn": "08:00",
            "DateOut": "2023-01-01",
            "HourOut": "16:00"
        }
        
+ Response 201 (application/json)

        {
            "RegisterID": 1,
            "GateID": 1,
            "DateIn": "2023-01-01",
            "HourIn": "08:00",
            "DateOut": "2023-01-01",
            "HourOut": "16:00"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### Read Register [GET]
+ Response 200 (application/json)

        {
            
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### Delete Register [DELETE]
+ Request

        {
            "RegisterID": 1,
        }
        
+ Response 200 (application/json)

        {
            "GateID": 1,
            "DateIn": "2023-01-01",
            "HourIn": "08:00",
            "DateOut": "2023-01-01",
            "HourOut": "16:00"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### Update Register [PUT]
+ Request

        {
            "GateID": 1,
            "DateIn": "2023-01-01",
            "HourIn": "08:00",
            "DateOut": "2023-01-01",
            "HourOut": "16:00"
        }
        
+ Response 200 (application/json)

        {
            "RegisterID": 1,
            "GateID": 1,
            "DateIn": "2023-01-01",
            "HourIn": "08:00",
            "DateOut": "2023-01-01",
            "HourOut": "16:00"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }
 
+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
        

# Group Leave API

## Leave [/leaves/{?LeaveID,EmployeeID,DateStart,DateEnd,LeaveType,Decision}]

+ Parameters

    + LeaveID (int) - Leave's ID
    + EmployeeID (int) - Employee's ID
    + DateStart (date) - Start date of leave
    + DateEnd (date) - End date of leave
    + LeaveType (string) - Leave's type
    + Decision (bool) - Manager's approval/refusal of leave

### Add New Leave [POST]
+ Request

        {
            "EmployeeID": 1,
            "StartDate": "2.1.2023",
            "EndDate": "3.1.2023",
            "LeaveType": "sick",
            "Acceptance": 1
        }
        
+ Response 201 (application/json)

        {
            "LeaveID": 1,
            "EmployeeID": 1,
            "StartDate": "2.1.2023",
            "EndDate": "3.1.2023",
            "LeaveType": "sick",
            "Acceptance": 1
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### Update Leave [PUT]
+ Request 

        {
            "LeaveID": 1,
            "EmployeeID": 1,
            "StartDate": "2.1.2023",
            "EndDate": "3.1.2023",
            "LeaveType": "sick",
            "Acceptance": 1
        }

+ Response 200 (application/json)

        {
            "LeaveID": 1,
            "EmployeeID": 1,
            "StartDate": "2.1.2023",
            "EndDate": "3.1.2023",
            "LeaveType": "sick",
            "Acceptance": 1
        }

+ Response 400 (text/plain)

        {
            "Message": "Bad Request"
        }
        
+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }