FORMAT: 1A
HOST: https://systemgenerowaniakartczasupracy.apiblueprint.org/

# System of generating employees' clockcards

It is an API


# Group User API

## User [/users/{?Login,Password,FirstName,LastName,AccountType,Email,AccountNo}]

+ Parameters

    + Login (string) - User's login
    + Password (int) - User's password
    + FirstName (string) - User's first name
    + LastName (string) - User's last name
    + AccountType (enum) - User's type of account
    + Email (string) - User's e-mail address
    + AccountNo (string) - User's login

### Add New User [POST]
+ Request

        {
            "Login": "jankow4822",
            "Password": 4932
            "FirstName": "Jan",
            "LastName": "Kowalski",
            "AccountType": "Employee",
            "E-mail": "jankowalski@gmail.com",
            "AccountNo": "PL11240000000000009999117429"
        }
        
+ Response 200 (application/json)

        {
            "Meesage": "Add: Done."
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }
        
### Edit User [PUT]
+ Response 200 (application/json)

        {
            "Meesage": "Edit: Done."
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

### Delete User [DELETE]
+ Response 200 (application/json)

        {
            "Meesage": "Delete: Done."
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

### List All Users [GET]
+ Response 200 (application/json)

        {
            
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }


# Group Employee API

## Employee [/employee/{?EmployeeID,Login,Department,ManagerID,PositionID}]

+ Parameters

    + EmployeeID (int) - Employee's ID
    + Login (string) - Employee's login
    + Department (string) - Employee's department
    + ManagerID (int) - Employee's manager's ID
    + PositionID (int) - Employee's position's ID

### Add New Employee [POST/employees/EmployeeID={EmployeeID}&Login={Login}&Department={Department}&ManagerID={ManagerID}&PositionID={PositionID]
+ Request

        {
            "EmployeeID": 10010422,
            "Login": "jankow4822",
            "Department": "DepA",
            "ManagerID": 101,
            "PositionID": 53
        }
        
+ Response 200 (application/json)

        {
            "Meesage": "Add: Done."
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }
        
### Edit Employee [PUT/users/EmployeeID={EmployeeID}&Login={Login}&Department={Department}&ManagerID={ManagerID}&PositionID={PositionID}]
+ Response 200 (application/json)

        {
            "Meesage": "Edit: Done."
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

### Delete Employee [DELETE/employees/EmployeeID={EmployeeID}]
+ Response 200 (application/json)

        {
            "Meesage": "Delete: Done."
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

### List All Employees [GET]
+ Request (application/json)

    + Headers 
        
            Authentication: Token

+ Response 200 (application/json)

    + Body

            {    
                [
                    {
                        "Message": "List of all employees: ",
                        "employees": 
                        [
                            {
                                "EmployeeID": 10010422,
                                "Login": "jankow4822",
                                "Department": "DepA",
                                "ManagerID": 101,
                                "PositionID": 53
                            }, {
                                "EmployeeID": 10010432,
                                "Login": "jankow4822",
                                "Department": "DepA",
                                "ManagerID": 101,
                                "PositionID": 53
                            }, {
                                "EmployeeID": 10010420,
                                "Login": "jankow4822",
                                "Department": "DepA",
                                "ManagerID": 101,
                                "PositionID": 53
                            }, 
                        ]
                    }
                ]
            }
            
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }
  
            
# Group Manager API

## Manager [/managers/{?ManagerID,Login}]

+ Parameters

    + ManagerID (int) - Manager's ID
    + Login (string) - Manager's login

### Add New Manager [POST]
+ Response 200 (application/json)

        {
            "Meesage": "Add: Done."
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

### Delete Manager [DELETE]
+ Response 200 (application/json)

        {
            "Meesage": "Delete: Done."
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

### List All Managers [GET]
+ Response 200 (application/json)

        {
            
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }


# Group Position API

## Position [/positions/{?PositionID,PositionName,Salary}]

+ Parameters

    + PositionID (int) - Position's ID
    + PositionName (string) - Position name's
    + Salary (int) - Salary assigned to position

### List All Positions [POST]
+ Response 200 (application/json)

        {
        
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }


# Group Gate API

## Gate [/gates/{?GateID,Login}]

+ Parameters

    + GateID (int) - Gate's ID
    + Login (string) - User's login


# Group Register API

## Register [/registers/{?EmployeeID,GateID,DateIn,HourIn,DateOut,HourOut}]

+ Parameters

    + EmployeeID (int) - Employee's ID
    + GateID (int) - Gate's ID
    + DateIn (date) - Start date of work
    + HourIn (time) - Start time of work
    + DateOut (date) - End date of work
    + HourOut (time) - End time of work


# Group Leave API

## Leave [/leaves/{?LeaveID,EmployeeID,DateStart,DateEnd,LeaveType,Decision}]

+ Parameters

    + LeaveID (int) - Leave's ID
    + EmployeeID (int) - Employee's ID
    + DateStart (date) - Start date of leave
    + DateEnd (date) - End date of leave
    + LeaveType (string) - Leave's type
    + Decision (bool) - Manager's approval/refusal of leave

### Add New Leave [POST]
+ Response 200 (application/json)

        {
            "Meesage": "Add: Done."
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }