-- WSTEPNA BAZA CZY WGL ZADZIALAJA POLACZENIA
-- TYPY DANYCH TRZEBA OGARNAC
-- GENERATOR LOSOWYCH DANYCH JESZCZE ZROBIC (ZEBY NA CZYMS DZIALAC)
-- NOT NULL CHYBA WSZEDZIE, BO CHYBA WSZEDZIE MUSI BYC JAKAS WARTOSC

CREATE TABLE USERS 		--ZMIENILAM NA L.MNOGA BO USER JEST TAKIE POLECENIE (I WTEDY COS BYLO NIE TAK)
(Login VARCHAR2(20) NOT NULL,
	CONSTRAINT PK_USERS PRIMARY KEY (Login),
Password VARCHAR2(20) NOT NULL,		-- OGOLNIE TU BEDZIE JUZ ZASZYFROWANE HASLO (FUNKCJE SZYFRUJACA OGARNAC), STRING  BO WIEKSZE BEZPIECZENSTWO
FirstName VARCHAR2(25) NOT NULL,
LastName VARCHAR2(25) NOT NULL,
AccountType VARCHAR2(25) NOT NULL,	-- TUTAJ MA BYC ENUM I TYP WRITE/READ/CREATE(TO JESZCZE DO OGARNIECIA, POCZYTANIA)
Email VARCHAR2(25) NOT NULL,
AccountNo VARCHAR2(25) NOT NULL
);

CREATE TABLE GATE
(GateID NUMBER(8) NOT NULL,
	CONSTRAINT PK_Gate PRIMARY KEY (GateID),
Login VARCHAR2(30) NOT NULL,
	CONSTRAINT FK_USERS
		FOREIGN KEY (Login)
		REFERENCES USERS(Login)
);

CREATE TABLE MANAGER
(ManagerID NUMBER(8) NOT NULL,
	CONSTRAINT PK_MANAGER PRIMARY KEY (ManagerID),
Login VARCHAR2(30) NOT NULL,
	CONSTRAINT FK_USERS
		FOREIGN KEY (Login)
		REFERENCES USERS(Login)
);

CREATE TABLE POSITION
(PositionID NUMBER(8) NOT NULL,
	CONSTRAINT PK_MANAGER PRIMARY KEY (PositionID),
PositionName VARCHAR2(30) NOT NULL,
Salary NUMBER(8) NOT NULL
);

CREATE TABLE EMPLOYEE
(EmployeeID NUMBER(8) NOT NULL,
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EmployeeID),
Login VARCHAR2(30) NOT NULL,
	CONSTRAINT FK_USERS
		FOREIGN KEY (Login)
		REFERENCES USERS(Login),
Department VARCHAR2(25) NOT NULL,	
ManagerID NUMBER(8) NOT NULL,
	CONSTRAINT FK_MANAGER
		FOREIGN KEY (ManagerID)
		REFERENCES MANAGER(ManagerID),
PositionID NUMBER(8),
	CONSTRAINT FK_POSITION
		FOREIGN KEY (PositionID)
		REFERENCES POSITION(PositionID)
);

CREATE TABLE REGISTER
(RegisterID NUMBER(8) NOT NULL,
	CONSTRAINT PK_POZYCZKI PRIMARY KEY (RegisterID),
EmployeeID NUMBER(8),
	CONSTRAINT FK_EMPLOYEE
		FOREIGN KEY (EmployeeID)
		REFERENCES EMPLOYEE(EmployeeID),
GateID NUMBER(8) NOT NULL,
	CONSTRAINT FK_GATE
		FOREIGN KEY (GateID)
		REFERENCES GATE(GateID),
DateIn DATE NOT NULL,
TimeIn DATE NOT NULL,		-- OGARNAC TYP DANYCH DO CZASU (TIME?) 
DateOut DATE NOT NULL,
TimeOut DATE NOT NULL		-- OGARNAC TYP DANYCH DO CZASU (TIME?) 
);

CREATE TABLE LEAVE
(LeaveID NUMBER(8) NOT NULL,
	CONSTRAINT PK_LEAVE PRIMARY KEY (LeaveID),
EmployeeID NUMBER(8),
	CONSTRAINT FK_EMPLOYEE
		FOREIGN KEY (EmployeeID)
		REFERENCES EMPLOYEE(EmployeeID),
StartDate DATE NOT NULL,
EndDate DATE NOT NULL,
LeaveType VARCHAR2(25) NOT NULL,	-- TUTAJ MA BYC ENUM I WARTOSCI M.IN. ZWOLNIENIE LEKARSKIE ITD
Decision NUMBER(2) NOT NULL 		-- WSTEPNIE LICZBA, ALE MYSLE ZEBY MOZE TO BYL BOOL (1, 0) CZY ZAAKCEPTOWANO
);

-- INICJOWANIE SKRYPTU Z DANYMI KONKRETNYMI (INSERT), NA RAZIE GO NIE MA ALE BEDZIE; PRZY URUCHAMIANIU SKRYPTU CreateWorkDB OD RAZU PO STWORZENIU TABEL, URUCHOMI SKRYPT Z DANYMI I POWSTAWIA DANE:
--Prompt skrypt_dane		
--@@skrypt_dane